name: Automatically register issues in Kanban

on:
  issues:
    types: [opened]

jobs:
  register issues in Kanban:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: 開発
          column: やる
          repo-token: ${{ secrets.GITHUB_TOKEN }}
